### ISSUE TITLE
Config not reading

### ISSUE THREAD

**Issue by gmarlett** [sebastiaanluca/laravel-4-eventcron#1]
I am able to queue events, but when I run flush, it fails because Config::get('eventcron::config.enabled') returns null

**Comment by sebastiaanluca** [comment]
Still an issue?

**Comment by gmarlett** [comment]
Yeah, I wasn't able to get it to read values from the config file after a while of fiddling.  So, before I call EventCron::flush I'm having to put this first:
            Config::set('eventcron::config.enabled', TRUE);
            Config::set('eventcron::config.run_only_from_cli', FALSE);
            Config::set('eventcron::config.max_events_per_execution', 20);
            Config::set('eventcron::config.log_events', false);

**Comment by sebastiaanluca** [comment]
Pushed version 0.3 with some fixes and a readme, including the configuration problem. Let me know how it works out for you.
