### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Schema\Schema::create()

### ISSUE THREAD

**Issue by louim** [sebastiaanluca/laravel-4-eventcron#2]
```
PHP Fatal error:  Call to undefined method Doctrine\DBAL\Schema\Schema::create() in /Users/louim/Work/desjardins_evenements_v2/app/database/migrations/2014_04_22_230122_cossou_eventcron_create_base_table.php on line 15
```

All work when removing "use Doctrine\DBAL\Schema\Schema;" from the migration file.

**Comment by sebastiaanluca** [comment]
Ah yes, I wasn't including Doctrine in my composer.json which is now optional with a Laravel installation. But if it works without, even better! Thanks for the fix, I'll get that merged right away :)
